on: push
name: Deploy to sternbauer.eu
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get latest version of page
        uses: actions/checkout@v4
      - name: Sync files with FTP-Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          server-dir: ./main/
          exclude: | 
            **/.git*
            **/.git*/**
            README.md
            LICENSE
            .gitignore
